DEFRA/adp-software-templates

catalog-model/org-templates.yaml
This PR contains changes to add the new frontend and backend templates to the configuration YAML file so that they can be displayed in the ADP Portal.
Removed the reference to the old template as it will not be used. 
Relates to ADO Work Item [AB#285385](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/285385)
- [ X] Story Work items associated (not Tasks)
- [ X] Title pattern should be `{work item number}: {title}`
- [ X] Description covers all the changes in the PR
=> 285385: Added the templates to the org-templates.YAML file so that they can be displayed in the ADP Portal

templates/adp-backend-template-node/skeleton/Dockerfile, templates/adp-frontend-template-node/skeleton/Dockerfile, templates/adp-frontend-template-node/skeleton/app/plugins/views.js
This PR contains cleanup of software templates. 
[AB#285385](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/285385)
=> 285385: Cleanup of software templates

templates/adp-backend-template-node/skeleton/.azuredevops/build.yaml, templates/adp-backend-template-node/skeleton/jest.config.js, templates/adp-backend-template-node/skeleton/package-lock.json, templates/adp-backend-template-node/skeleton/package.json, templates/adp-backend-template-node/skeleton/test/mocks/application-insights.js, templates/adp-backend-template-node/skeleton/test/unit/index.test.js, templates/adp-backend-template-node/skeleton/test/unit/insights.test.js, templates/adp-backend-template-node/skeleton/test/unit/routes/healthy.test.js, templates/adp-backend-template-node/skeleton/test/unit/routes/healthz.test.js, templates/adp-backend-template-node/skeleton/test/unit/server.test.js, templates/adp-frontend-template-node/skeleton/app/index.js, templates/adp-frontend-template-node/skeleton/app/views/_layout.template.njk, templates/adp-frontend-template-node/skeleton/jest.config.js, templates/adp-frontend-template-node/skeleton/package-lock.json, templates/adp-frontend-template-node/skeleton/package.json, templates/adp-frontend-template-node/skeleton/test/mocks/application-insights.js, templates/adp-frontend-template-node/skeleton/test/unit/index.test.js, templates/adp-frontend-template-node/skeleton/test/unit/insights.test.js, templates/adp-frontend-template-node/skeleton/test/unit/plugins/router.test.js, templates/adp-frontend-template-node/skeleton/test/unit/plugins/views.test.js, templates/adp-frontend-template-node/skeleton/test/unit/routes/healthy.test.js, templates/adp-frontend-template-node/skeleton/test/unit/routes/healthz.test.js, templates/adp-frontend-template-node/skeleton/test/unit/routes/home.test.js, templates/adp-frontend-template-node/skeleton/test/unit/routes/static.test.js, templates/adp-frontend-template-node/skeleton/test/unit/server.test.js
This PR contains the changes to add unit tests for frontend and backend node software templates
[AB#299229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/299229)
=> 299229: Added unit tests for software templates

templates/adp-backend-template-node/skeleton/.pre-commit-config.yaml, templates/adp-backend-template-node/skeleton/.secrets.baseline, templates/adp-backend-template-node/skeleton/README.md, templates/adp-backend-template-node/skeleton/db-migration.Dockerfile, templates/adp-backend-template-node/skeleton/docker-compose.link.yaml, templates/adp-backend-template-node/skeleton/docker-compose.migrate.yaml, templates/adp-backend-template-node/skeleton/docker-compose.override.yaml, templates/adp-backend-template-node/skeleton/docker-compose.yaml, templates/adp-backend-template-node/skeleton/scripts/migration/database-up, templates/adp-backend-template-node/template.yaml
This PR contains the fixes for database migration for local development.
Added docker-compose.migrate.yaml
- Fixed migration scripts
- Fixed db-migration.dockerfile
- Updated pre-commit version
[AB#299229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/299229)
=> 299229: Fixes for local development

templates/adp-backend-template-node/skeleton/helm/${{ values.project_name }}-infra/values.yaml, templates/adp-backend-template-node/skeleton/helm/${{ values.project_name }}/values.yaml, templates/adp-frontend-template-node/skeleton/helm/${{ values.project_name }}-infra/values.yaml, templates/adp-frontend-template-node/skeleton/helm/${{ values.project_name }}/values.yaml
*A brief description of changes being made*
Updated the HELM Charts for the scaffolded templates, with comments and doc improvements.
=> Update software templates - HELM Charts

templates/adp-backend-template-node/skeleton/helm/${{ values.project_name }}/values.yaml, templates/adp-frontend-template-node/skeleton/helm/${{ values.project_name }}/values.yaml
An issue on HELM Lint requires the deployment empty block to be put back in.
=> Add back in the deployment block to fix bug

templates/adp-backend-template-node/skeleton/helm/${{ values.project_name }}-infra/values.yaml, templates/adp-backend-template-node/skeleton/helm/${{ values.project_name }}/values.yaml, templates/adp-frontend-template-node/skeleton/helm/${{ values.project_name }}/values.yaml
Owner should be set to 'no' if queue receiver.
we need to remove this validation in future
Need to also set Port number
=> Update values.yaml to fix deployment bugs

templates/adp-frontend-template-node/skeleton/.gitignore
[AB#337921](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/337921)
Remove auth from .gitignore to track the changes of auth folder in repo
auth removed from .gitignore file
=> 337921: Remove auth from exclusions in .gitignore

templates/adp-backend-template-node/skeleton/package-lock.json, templates/adp-backend-template-node/skeleton/package.json, templates/adp-frontend-template-node/skeleton/package-lock.json, templates/adp-frontend-template-node/skeleton/package.json
The ^ (caret) character in dependencies is not recommended as it can result in different behaviour between container rebuilds which may make the service unpredictable/unstable.  This PR removes the caret from Jest Types dependencies
[AB#337918](https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Team%20Fab/DEFRA-FFC/Platform/Fab/Sprint13?workitem=337918)
N/A
N/A
=> 337918 : Fixes Jest Dependencies

templates/adp-backend-template-node/template.yaml, templates/adp-empty-project-template/template.yaml, templates/adp-frontend-template-node/template.yaml
This reverts commit 88459c72798539a8e85abc8f5a29fb939a07c2c0.
Reverts #43 to allow pentesters to continue with their work. This revert will be reverted later
[AB#345221](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/345221)
=> Revert "345221: Templates add service to the flux config (#43)"

templates/adp-backend-template-node/template.yaml, templates/adp-empty-project-template/template.yaml, templates/adp-frontend-template-node/template.yaml
Re-implements the changes made in #43 and reverted in #45.
[AB#345221](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/345221)
=> 345221: Template to add service to flux config

templates/adp-backend-template-node/template.yaml, templates/adp-empty-project-template/template.yaml, templates/adp-frontend-template-node/template.yaml, templates/adp-helm-only-template/template.yaml
[AB#358695](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/358695)
This PR updates the scaffolder templates to make use of the new github teams flow. The old teams related questions have been removed and the team create/assign steps has been replaced with a single step to do both.
=> 358695: templates use new git team flow

templates/adp-backend-template-node/template.yaml, templates/adp-frontend-template-node/template.yaml, templates/adp-helm-only-template/template.yaml
This PR contains the changes to generate flux manifests for helm only template
[AB#346049](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/346049)
=> 346049: Updated Helm Only template to generate flux manifests

templates/adp-backend-template-node/template.yaml, templates/adp-frontend-template-node/template.yaml, templates/adp-helm-only-template/template.yaml
*A brief description of changes being made*
*Link to the relevant work items: *
[AB#361984](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/361984)
=> 361984: Prod service connection and agent pool

templates/adp-backend-template-node/template.yaml
[AB#378196](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/378196) Set the `POSTGRES_DB` config variable if the user has chosen to use a database in the backend template.
=> 378196: Add in postgres db config variable

templates/adp-backend-template-dotnet/skeleton/.azuredevops/build.yaml
Bug fix for build.yaml to render devops parameters as it is on dotnet template
[AB#275171](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/275171)
=> 275171: Fixed build.yaml on dotnet template

templates/adp-backend-template-node/template.yaml
[AB#378196](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/378196) Fixes an issue where the POSTGRES_DB variable needs to include the team name
=> 378196: Add team name as prefix to postgres config variable

templates/adp-backend-template-dotnet/skeleton/appConfig/appConfig.snd4.yaml, templates/adp-backend-template-dotnet/template.yaml, templates/adp-backend-template-node/skeleton/appConfig/appConfig.snd4.yaml, templates/adp-backend-template-node/template.yaml, templates/adp-frontend-template-node/skeleton/appConfig/appConfig.snd4.yaml, templates/adp-frontend-template-node/template.yaml, templates/adp-helm-only-template/template.yaml
Added snd4 in template environments & appconfig file.
[AB#334259](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/334259)
=> 334259: Added snd4 & ssv5

templates/adp-helm-only-template/skeleton/.azuredevops/ingress-helm-publish.yaml
Removed includePlatformEnvs from pipeline
[AB#393544](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/393544)
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
=> 393544: Removed includePlatformEnvs from pipeline

templates/adp-helm-only-template/template.dev.yaml, templates/adp-helm-only-template/template.yaml
Templating failed if a user set the defaultPath as empty
Fixes the INGRESS_ENDPOINT value
=> Update handling of defaultPath

templates/adp-backend-template-dotnet/template.dev.yaml, templates/adp-backend-template-dotnet/template.yaml, templates/adp-backend-template-node/template.dev.yaml, templates/adp-backend-template-node/template.yaml, templates/adp-empty-project-template/template.dev.yaml, templates/adp-empty-project-template/template.yaml, templates/adp-frontend-template-node/template.dev.yaml, templates/adp-frontend-template-node/template.yaml, templates/adp-helm-only-template/template.dev.yaml, templates/adp-helm-only-template/template.yaml, templates/parameters/git-repository.yaml, templates/steps/ado-create-pipeline.yaml, templates/steps/github-publish.yaml, templates/steps/github-team.yaml
[AB#399260](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399260) Updates the git repository picker to only allow the correct defra organization per environment
=> 399260: Update git repository picker

templates/adp-backend-template-node/skeleton/${{ 'db-migration.Dockerfile' if values.app_infra_postgres_db_check == 'yes' }}
Update the db-migration.Dockerfile to use ADP PostgreSql migration image
[AB#400560](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/400560)
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
=> 400560:Update db-migration.Dockerfile
